apiVersion: v1
kind: Service
metadata:
  name: wisdon-frontend
  namespace: wisdon
  labels:
    app: wisdon-frontend
spec:
  type: NodePort
  selector:
    app: wisdon-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
