version: '3.1'

services:
  flask_web:
    build:
      context: ./
      dockerfile: ./flask-web.Dockerfile
    container_name: oran-flask-web
    restart: unless-stopped
    ports:
      - "2880:2880"
    volumes:
      - ./img:/app/img
    environment:
      FLASK_ENV: development
      TZ: Asia/Taipei
