apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wisdon-frontend

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: frontend
  project: wisdon
  managed-by: kustomize
