apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: wisdon-frontend
type: Opaque
stringData:
  DB_HOST: "mysql"
  DB_DATABASE: "devdb"
  DB_USER: "root"
  DB_PASSWORD: "wisdon2024"
  SECRET_KEY: "wisdon_secret_key_2024"
  INFLUXDB_HOST: "influxdb"
  INFLUXDB_PORT: "8086"
  INFLUXDB_DB: "wisdon"
  INFLUXDB_ADMIN_USER: "admin"
  INFLUXDB_ADMIN_PASSWORD: "wisdon2024"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "wisdon2024"
  GRAFANA_URL: "http://grafana:3000"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "wisdon2024"
  MINIO_SECURE: "false"
  CELERY_BROKER: "redis://redis:6379/0"
  CELERY_BACKEND: "redis://redis:6379/0"
  NOMINATIM_API_URL: "https://nominatim.openstreetmap.org/search"
  MYSQL_ROOT_PASSWORD: "wisdon2024"
  MYSQL_DATABASE: "devdb"
